using AutoMapper;
using CTI.ELMS.API.Controllers.v1;
using CTI.ELMS.Application.Features.ELMS.PPlusConnectionSetup.Commands;
using CTI.ELMS.Application.Features.ELMS.EntityGroup.Commands;
using CTI.ELMS.Application.Features.ELMS.Project.Commands;
using CTI.ELMS.Application.Features.ELMS.UserProjectAssignment.Commands;
using CTI.ELMS.Application.Features.ELMS.Unit.Commands;
using CTI.ELMS.Application.Features.ELMS.UnitBudget.Commands;
using CTI.ELMS.Application.Features.ELMS.LeadSource.Commands;
using CTI.ELMS.Application.Features.ELMS.LeadTouchPoint.Commands;
using CTI.ELMS.Application.Features.ELMS.LeadTask.Commands;
using CTI.ELMS.Application.Features.ELMS.NextStep.Commands;
using CTI.ELMS.Application.Features.ELMS.ClientFeedback.Commands;
using CTI.ELMS.Application.Features.ELMS.LeadTaskClientFeedBack.Commands;
using CTI.ELMS.Application.Features.ELMS.LeadTaskNextStep.Commands;
using CTI.ELMS.Application.Features.ELMS.BusinessNature.Commands;
using CTI.ELMS.Application.Features.ELMS.BusinessNatureSubItem.Commands;
using CTI.ELMS.Application.Features.ELMS.BusinessNatureCategory.Commands;
using CTI.ELMS.Application.Features.ELMS.OperationType.Commands;
using CTI.ELMS.Application.Features.ELMS.Salutation.Commands;
using CTI.ELMS.Application.Features.ELMS.Lead.Commands;
using CTI.ELMS.Application.Features.ELMS.Contact.Commands;
using CTI.ELMS.Application.Features.ELMS.ContactPerson.Commands;
using CTI.ELMS.Application.Features.ELMS.Activity.Commands;
using CTI.ELMS.Application.Features.ELMS.UnitActivity.Commands;
using CTI.ELMS.Application.Features.ELMS.Offering.Commands;
using CTI.ELMS.Application.Features.ELMS.PreSelectedUnit.Commands;
using CTI.ELMS.Application.Features.ELMS.UnitOffered.Commands;
using CTI.ELMS.Application.Features.ELMS.UnitGroup.Commands;
using CTI.ELMS.Application.Features.ELMS.AnnualIncrement.Commands;
using CTI.ELMS.Application.Features.ELMS.IFCATransactionType.Commands;
using CTI.ELMS.Application.Features.ELMS.IFCATenantInformation.Commands;
using CTI.ELMS.Application.Features.ELMS.IFCAUnitInformation.Commands;
using CTI.ELMS.Application.Features.ELMS.IFCAARLedger.Commands;
using CTI.ELMS.Application.Features.ELMS.IFCAARAllocation.Commands;
using CTI.ELMS.Application.Features.ELMS.ReportTableCollectionDetail.Commands;
using CTI.ELMS.Application.Features.ELMS.ReportTableYTDExpirySummary.Commands;


namespace CTI.ELMS.API;

public class MappingProfile : Profile
{
    public MappingProfile()
    {
        CreateMap<PPlusConnectionSetupViewModel, AddPPlusConnectionSetupCommand>();
		CreateMap <PPlusConnectionSetupViewModel, EditPPlusConnectionSetupCommand>();
		CreateMap<EntityGroupViewModel, AddEntityGroupCommand>();
		CreateMap <EntityGroupViewModel, EditEntityGroupCommand>();
		CreateMap<ProjectViewModel, AddProjectCommand>();
		CreateMap <ProjectViewModel, EditProjectCommand>();
		CreateMap<UserProjectAssignmentViewModel, AddUserProjectAssignmentCommand>();
		CreateMap <UserProjectAssignmentViewModel, EditUserProjectAssignmentCommand>();
		CreateMap<UnitViewModel, AddUnitCommand>();
		CreateMap <UnitViewModel, EditUnitCommand>();
		CreateMap<UnitBudgetViewModel, AddUnitBudgetCommand>();
		CreateMap <UnitBudgetViewModel, EditUnitBudgetCommand>();
		CreateMap<LeadSourceViewModel, AddLeadSourceCommand>();
		CreateMap <LeadSourceViewModel, EditLeadSourceCommand>();
		CreateMap<LeadTouchPointViewModel, AddLeadTouchPointCommand>();
		CreateMap <LeadTouchPointViewModel, EditLeadTouchPointCommand>();
		CreateMap<LeadTaskViewModel, AddLeadTaskCommand>();
		CreateMap <LeadTaskViewModel, EditLeadTaskCommand>();
		CreateMap<NextStepViewModel, AddNextStepCommand>();
		CreateMap <NextStepViewModel, EditNextStepCommand>();
		CreateMap<ClientFeedbackViewModel, AddClientFeedbackCommand>();
		CreateMap <ClientFeedbackViewModel, EditClientFeedbackCommand>();
		CreateMap<LeadTaskClientFeedBackViewModel, AddLeadTaskClientFeedBackCommand>();
		CreateMap <LeadTaskClientFeedBackViewModel, EditLeadTaskClientFeedBackCommand>();
		CreateMap<LeadTaskNextStepViewModel, AddLeadTaskNextStepCommand>();
		CreateMap <LeadTaskNextStepViewModel, EditLeadTaskNextStepCommand>();
		CreateMap<BusinessNatureViewModel, AddBusinessNatureCommand>();
		CreateMap <BusinessNatureViewModel, EditBusinessNatureCommand>();
		CreateMap<BusinessNatureSubItemViewModel, AddBusinessNatureSubItemCommand>();
		CreateMap <BusinessNatureSubItemViewModel, EditBusinessNatureSubItemCommand>();
		CreateMap<BusinessNatureCategoryViewModel, AddBusinessNatureCategoryCommand>();
		CreateMap <BusinessNatureCategoryViewModel, EditBusinessNatureCategoryCommand>();
		CreateMap<OperationTypeViewModel, AddOperationTypeCommand>();
		CreateMap <OperationTypeViewModel, EditOperationTypeCommand>();
		CreateMap<SalutationViewModel, AddSalutationCommand>();
		CreateMap <SalutationViewModel, EditSalutationCommand>();
		CreateMap<LeadViewModel, AddLeadCommand>();
		CreateMap <LeadViewModel, EditLeadCommand>();
		CreateMap<ContactViewModel, AddContactCommand>();
		CreateMap <ContactViewModel, EditContactCommand>();
		CreateMap<ContactPersonViewModel, AddContactPersonCommand>();
		CreateMap <ContactPersonViewModel, EditContactPersonCommand>();
		CreateMap<ActivityViewModel, AddActivityCommand>();
		CreateMap <ActivityViewModel, EditActivityCommand>();
		CreateMap<UnitActivityViewModel, AddUnitActivityCommand>();
		CreateMap <UnitActivityViewModel, EditUnitActivityCommand>();
		CreateMap<OfferingViewModel, AddOfferingCommand>();
		CreateMap <OfferingViewModel, EditOfferingCommand>();
		CreateMap<PreSelectedUnitViewModel, AddPreSelectedUnitCommand>();
		CreateMap <PreSelectedUnitViewModel, EditPreSelectedUnitCommand>();
		CreateMap<UnitOfferedViewModel, AddUnitOfferedCommand>();
		CreateMap <UnitOfferedViewModel, EditUnitOfferedCommand>();
		CreateMap<UnitGroupViewModel, AddUnitGroupCommand>();
		CreateMap <UnitGroupViewModel, EditUnitGroupCommand>();
		CreateMap<AnnualIncrementViewModel, AddAnnualIncrementCommand>();
		CreateMap <AnnualIncrementViewModel, EditAnnualIncrementCommand>();	
		CreateMap<IFCATransactionTypeViewModel, AddIFCATransactionTypeCommand>();
		CreateMap <IFCATransactionTypeViewModel, EditIFCATransactionTypeCommand>();
		CreateMap<IFCATenantInformationViewModel, AddIFCATenantInformationCommand>();
		CreateMap <IFCATenantInformationViewModel, EditIFCATenantInformationCommand>();
		CreateMap<IFCAUnitInformationViewModel, AddIFCAUnitInformationCommand>();
		CreateMap <IFCAUnitInformationViewModel, EditIFCAUnitInformationCommand>();
		CreateMap<IFCAARLedgerViewModel, AddIFCAARLedgerCommand>();
		CreateMap <IFCAARLedgerViewModel, EditIFCAARLedgerCommand>();
		CreateMap<IFCAARAllocationViewModel, AddIFCAARAllocationCommand>();
		CreateMap <IFCAARAllocationViewModel, EditIFCAARAllocationCommand>();
		CreateMap<ReportTableCollectionDetailViewModel, AddReportTableCollectionDetailCommand>();
		CreateMap <ReportTableCollectionDetailViewModel, EditReportTableCollectionDetailCommand>();
		CreateMap<ReportTableYTDExpirySummaryViewModel, AddReportTableYTDExpirySummaryCommand>();
		CreateMap <ReportTableYTDExpirySummaryViewModel, EditReportTableYTDExpirySummaryCommand>();
		
    }
}
